# -*- coding: utf-8 -*-
"""Skill gap analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ad-cbd8WiBRZL0CRhYF3W76gSqdZFUmf
"""

pip install pandas numpy scikit-learn networkx xgboost pdfplumber matplotlib sentence-transformers

import pandas as pd
import numpy as np
import networkx as nx
import pdfplumber
from sklearn.preprocessing import MultiLabelBinarizer, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

df = pd.read_csv("job_dataset.csv")

print(df.columns)
print(df.head())

df['combined_skills'] = (df['Skills'] + ";" + df['Keywords']).fillna("").str.lower()

df['skill_list'] = df['combined_skills'].apply(
    lambda x: [s.strip() for s in x.split(";") if s.strip()]
)

def normalize(skill):
    return skill.replace("-", " ").replace("_", " ").strip().lower()

all_skills = set()

for skills in df['skill_list']:
    for skill in skills:
        all_skills.add(normalize(skill))

cleaned_skills = set(s for s in all_skills if len(s) > 2)

def extract_text(pdf_path):
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            if page.extract_text():
                text += page.extract_text() + " "
    return text

fy_text = extract_text("FYB Tech SVU R-2025 - Scheme and Detailed Syllabus.pdf")
sy_text = extract_text("10 Jan SY AIDS Syllabus (SVU-23)-with OEG.pdf")
ty_text = extract_text("TY BTech AI&DS-SVU-2023.pdf")

all_text = (fy_text + " " + sy_text + " " + ty_text).lower()

curriculum_skills = set()

for skill in cleaned_skills:
    if skill in all_text:
        curriculum_skills.add(skill)

curriculum_skill_list = list(curriculum_skills)

df['clean_role'] = df['Title'].astype(str).str.lower().str.strip()

role_skills = {}

for _, row in df.iterrows():
    role = row['clean_role']
    skills = set(row['skill_list'])

    role_skills.setdefault(role, set()).update(skills)

G = nx.Graph()

for skills in df['skill_list']:
    skills = list(set([s.strip().lower() for s in skills]))

    for i in range(len(skills)):
        for j in range(i+1, len(skills)):
            u, v = skills[i], skills[j]

            if G.has_edge(u, v):
                G[u][v]['weight'] = G[u][v].get('weight', 0) + 1
            else:
                G.add_edge(u, v, weight=1)

model = SentenceTransformer('all-MiniLM-L6-v2')

industry_skill_list = list(cleaned_skills)

industry_embeddings = model.encode(industry_skill_list)
curriculum_embeddings = model.encode(curriculum_skill_list)

def is_skill_covered(skill, threshold=0.6):

    skill_vec = model.encode([skill])

    similarities = cosine_similarity(skill_vec, curriculum_embeddings)

    return np.max(similarities) > threshold

def graph_similarity(skill):
    for cs in curriculum_skill_list:
        if G.has_edge(skill, cs):
            return True
    return False

def graph_similarity(skill):
    for cs in curriculum_skill_list:
        if G.has_edge(skill, cs):
            return True
    return False

def is_skill_covered_final(skill):
    if is_skill_covered(skill):
        return True

    if graph_similarity(skill):
        return True

    return False

role_gap = {}

for role, skills in role_skills.items():

    missing = []

    for skill in skills:
        if not is_skill_covered_final(skill):
            missing.append(skill)

    role_gap[role] = set(missing)

output_data = []

for role, skills in role_skills.items():

    total = len(skills)
    missing = role_gap[role]

    gap_percent = (len(missing)/total)*100 if total > 0 else 0

    output_data.append({
        "Role": role,
        "Total Skills": total,
        "Missing Skills": ", ".join(missing),
        "Missing Count": len(missing),
        "Gap %": round(gap_percent, 2)
    })

final_df = pd.DataFrame(output_data)

# Sort by highest gap
final_df = final_df.sort_values(by="Gap %", ascending=False)

final_df.to_csv("final_skill_gap.csv", index=False)

print("CSV Generated Successfully ")